=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kubevirt::IoK8sApimachineryPkgApisMetaV1ShardInfo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kubevirt::IoK8sApimachineryPkgApisMetaV1ShardInfo do
  #let(:instance) { Kubevirt::IoK8sApimachineryPkgApisMetaV1ShardInfo.new }

  describe 'test an instance of IoK8sApimachineryPkgApisMetaV1ShardInfo' do
    it 'should create an instance of IoK8sApimachineryPkgApisMetaV1ShardInfo' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kubevirt::IoK8sApimachineryPkgApisMetaV1ShardInfo)
    end
  end

  describe 'test attribute "selector"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
