=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kubevirt::IoK8sApiCoreV1TopologySpreadConstraint
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kubevirt::IoK8sApiCoreV1TopologySpreadConstraint do
  #let(:instance) { Kubevirt::IoK8sApiCoreV1TopologySpreadConstraint.new }

  describe 'test an instance of IoK8sApiCoreV1TopologySpreadConstraint' do
    it 'should create an instance of IoK8sApiCoreV1TopologySpreadConstraint' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kubevirt::IoK8sApiCoreV1TopologySpreadConstraint)
    end
  end

  describe 'test attribute "label_selector"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "match_label_keys"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "max_skew"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "min_domains"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "node_affinity_policy"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Honor", "Ignore"])
      # validator.allowable_values.each do |value|
      #   expect { instance.node_affinity_policy = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "node_taints_policy"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Honor", "Ignore"])
      # validator.allowable_values.each do |value|
      #   expect { instance.node_taints_policy = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "topology_key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "when_unsatisfiable"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["DoNotSchedule", "ScheduleAnyway"])
      # validator.allowable_values.each do |value|
      #   expect { instance.when_unsatisfiable = value }.not_to raise_error
      # end
    end
  end

end
