=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kubevirt::V1PersistentVolumeClaimInfo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kubevirt::V1PersistentVolumeClaimInfo do
  #let(:instance) { Kubevirt::V1PersistentVolumeClaimInfo.new }

  describe 'test an instance of V1PersistentVolumeClaimInfo' do
    it 'should create an instance of V1PersistentVolumeClaimInfo' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kubevirt::V1PersistentVolumeClaimInfo)
    end
  end

  describe 'test attribute "access_modes"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["ReadOnlyMany", "ReadWriteMany", "ReadWriteOnce", "ReadWriteOncePod"])
      # validator.allowable_values.each do |value|
      #   expect { instance.access_modes = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "capacity"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "claim_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "filesystem_overhead"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "preallocated"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "requests"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "volume_mode"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Block", "Filesystem", "FromStorageProfile"])
      # validator.allowable_values.each do |value|
      #   expect { instance.volume_mode = value }.not_to raise_error
      # end
    end
  end

end
