=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Kubevirt
  # APIResource specifies the name of a resource and whether it is namespaced.
  class IoK8sApimachineryPkgApisMetaV1APIResource < ApiModelBase
    # categories is a list of the grouped resources this resource belongs to (e.g. 'all')
    attr_accessor :categories

    # group is the preferred group of the resource.  Empty implies the group of the containing resource list. For subresources, this may have a different value, for example: Scale\".
    attr_accessor :group

    # kind is the kind for the resource (e.g. 'Foo' is the kind for a resource 'foo')
    attr_accessor :kind

    # name is the plural name of the resource.
    attr_accessor :name

    # namespaced indicates if a resource is namespaced or not.
    attr_accessor :namespaced

    # shortNames is a list of suggested short names of the resource.
    attr_accessor :short_names

    # singularName is the singular name of the resource.  This allows clients to handle plural and singular opaquely. The singularName is more correct for reporting status on a single item and both singular and plural are allowed from the kubectl CLI interface.
    attr_accessor :singular_name

    # The hash value of the storage version, the version this resource is converted to when written to the data store. Value must be treated as opaque by clients. Only equality comparison on the value is valid. This is an alpha feature and may change or be removed in the future. The field is populated by the apiserver only if the StorageVersionHash feature gate is enabled. This field will remain optional even if it graduates.
    attr_accessor :storage_version_hash

    # verbs is a list of supported kube verbs (this includes get, list, watch, create, update, patch, delete, deletecollection, and proxy)
    attr_accessor :verbs

    # version is the preferred version of the resource.  Empty implies the version of the containing resource list For subresources, this may have a different value, for example: v1 (while inside a v1beta1 version of the core resource's group)\".
    attr_accessor :version

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'categories' => :'categories',
        :'group' => :'group',
        :'kind' => :'kind',
        :'name' => :'name',
        :'namespaced' => :'namespaced',
        :'short_names' => :'shortNames',
        :'singular_name' => :'singularName',
        :'storage_version_hash' => :'storageVersionHash',
        :'verbs' => :'verbs',
        :'version' => :'version'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'categories' => :'Array<String>',
        :'group' => :'String',
        :'kind' => :'String',
        :'name' => :'String',
        :'namespaced' => :'Boolean',
        :'short_names' => :'Array<String>',
        :'singular_name' => :'String',
        :'storage_version_hash' => :'String',
        :'verbs' => :'Array<String>',
        :'version' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kubevirt::IoK8sApimachineryPkgApisMetaV1APIResource` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kubevirt::IoK8sApimachineryPkgApisMetaV1APIResource`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'categories')
        if (value = attributes[:'categories']).is_a?(Array)
          self.categories = value
        end
      end

      if attributes.key?(:'group')
        self.group = attributes[:'group']
      end

      if attributes.key?(:'kind')
        self.kind = attributes[:'kind']
      else
        self.kind = ''
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = ''
      end

      if attributes.key?(:'namespaced')
        self.namespaced = attributes[:'namespaced']
      else
        self.namespaced = false
      end

      if attributes.key?(:'short_names')
        if (value = attributes[:'short_names']).is_a?(Array)
          self.short_names = value
        end
      end

      if attributes.key?(:'singular_name')
        self.singular_name = attributes[:'singular_name']
      else
        self.singular_name = ''
      end

      if attributes.key?(:'storage_version_hash')
        self.storage_version_hash = attributes[:'storage_version_hash']
      end

      if attributes.key?(:'verbs')
        if (value = attributes[:'verbs']).is_a?(Array)
          self.verbs = value
        end
      else
        self.verbs = nil
      end

      if attributes.key?(:'version')
        self.version = attributes[:'version']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @kind.nil?
        invalid_properties.push('invalid value for "kind", kind cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @namespaced.nil?
        invalid_properties.push('invalid value for "namespaced", namespaced cannot be nil.')
      end

      if @singular_name.nil?
        invalid_properties.push('invalid value for "singular_name", singular_name cannot be nil.')
      end

      if @verbs.nil?
        invalid_properties.push('invalid value for "verbs", verbs cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @kind.nil?
      return false if @name.nil?
      return false if @namespaced.nil?
      return false if @singular_name.nil?
      return false if @verbs.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] kind Value to be assigned
    def kind=(kind)
      if kind.nil?
        fail ArgumentError, 'kind cannot be nil'
      end

      @kind = kind
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] namespaced Value to be assigned
    def namespaced=(namespaced)
      if namespaced.nil?
        fail ArgumentError, 'namespaced cannot be nil'
      end

      @namespaced = namespaced
    end

    # Custom attribute writer method with validation
    # @param [Object] singular_name Value to be assigned
    def singular_name=(singular_name)
      if singular_name.nil?
        fail ArgumentError, 'singular_name cannot be nil'
      end

      @singular_name = singular_name
    end

    # Custom attribute writer method with validation
    # @param [Object] verbs Value to be assigned
    def verbs=(verbs)
      if verbs.nil?
        fail ArgumentError, 'verbs cannot be nil'
      end

      @verbs = verbs
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          categories == o.categories &&
          group == o.group &&
          kind == o.kind &&
          name == o.name &&
          namespaced == o.namespaced &&
          short_names == o.short_names &&
          singular_name == o.singular_name &&
          storage_version_hash == o.storage_version_hash &&
          verbs == o.verbs &&
          version == o.version
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [categories, group, kind, name, namespaced, short_names, singular_name, storage_version_hash, verbs, version].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
