=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Kubevirt
  # DeveloperConfiguration holds developer options
  class V1DeveloperConfiguration < ApiModelBase
    # Enable the ability to pprof profile KubeVirt control plane
    attr_accessor :cluster_profiler

    # For each requested virtual CPU, CPUAllocationRatio defines how much physical CPU to request per VMI from the hosting node. The value is in fraction of a CPU thread (or core on non-hyperthreaded nodes). For example, a value of 1 means 1 physical CPU thread per VMI CPU thread. A value of 100 would be 1% of a physical thread allocated for each requested VMI thread. This option has no effect on VMIs that request dedicated CPUs. More information at: https://kubevirt.io/user-guide/operations/node_overcommit/#node-cpu-allocation-ratio Defaults to 10
    attr_accessor :cpu_allocation_ratio

    # DisabledFeatureGates specifies a list of experimental feature gates to disable. A feature gate must not appear in both FeatureGates and DisabledFeatureGates.
    attr_accessor :disabled_feature_gates

    attr_accessor :disk_verification

    # FeatureGates specifies a list of experimental feature gates to enable. Defaults to none. A feature gate must not appear in both FeatureGates and DisabledFeatureGates.
    attr_accessor :feature_gates

    attr_accessor :log_verbosity

    # MemoryOvercommit is the percentage of memory we want to give VMIs compared to the amount given to its parent pod (virt-launcher). For example, a value of 102 means the VMI will \"see\" 2% more memory than its parent pod. Values under 100 are effectively \"undercommits\". Overcommits can lead to memory exhaustion, which in turn can lead to crashes. Use carefully. Defaults to 100
    attr_accessor :memory_overcommit

    # Allow overriding the automatically determined minimum TSC frequency of the cluster and fixate the minimum to this frequency.
    attr_accessor :minimum_cluster_tsc_frequency

    # MinimumReservePVCBytes is the amount of space, in bytes, to leave unused on disks. Defaults to 131072 (128KiB)
    attr_accessor :minimum_reserve_pvc_bytes

    # NodeSelectors allows restricting VMI creation to nodes that match a set of labels. Defaults to none
    attr_accessor :node_selectors

    # LessPVCSpaceToleration determines how much smaller, in percentage, disk PVCs are allowed to be compared to the requested size (to account for various overheads). Defaults to 10
    attr_accessor :pvc_tolerate_less_space_up_to_percent

    # UseEmulation can be set to true to allow fallback to software emulation in case hardware-assisted emulation is not available. Defaults to false
    attr_accessor :use_emulation

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'cluster_profiler' => :'clusterProfiler',
        :'cpu_allocation_ratio' => :'cpuAllocationRatio',
        :'disabled_feature_gates' => :'disabledFeatureGates',
        :'disk_verification' => :'diskVerification',
        :'feature_gates' => :'featureGates',
        :'log_verbosity' => :'logVerbosity',
        :'memory_overcommit' => :'memoryOvercommit',
        :'minimum_cluster_tsc_frequency' => :'minimumClusterTSCFrequency',
        :'minimum_reserve_pvc_bytes' => :'minimumReservePVCBytes',
        :'node_selectors' => :'nodeSelectors',
        :'pvc_tolerate_less_space_up_to_percent' => :'pvcTolerateLessSpaceUpToPercent',
        :'use_emulation' => :'useEmulation'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'cluster_profiler' => :'Boolean',
        :'cpu_allocation_ratio' => :'Integer',
        :'disabled_feature_gates' => :'Array<String>',
        :'disk_verification' => :'V1DiskVerification',
        :'feature_gates' => :'Array<String>',
        :'log_verbosity' => :'V1LogVerbosity',
        :'memory_overcommit' => :'Integer',
        :'minimum_cluster_tsc_frequency' => :'Integer',
        :'minimum_reserve_pvc_bytes' => :'Integer',
        :'node_selectors' => :'Hash<String, String>',
        :'pvc_tolerate_less_space_up_to_percent' => :'Integer',
        :'use_emulation' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kubevirt::V1DeveloperConfiguration` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kubevirt::V1DeveloperConfiguration`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'cluster_profiler')
        self.cluster_profiler = attributes[:'cluster_profiler']
      end

      if attributes.key?(:'cpu_allocation_ratio')
        self.cpu_allocation_ratio = attributes[:'cpu_allocation_ratio']
      end

      if attributes.key?(:'disabled_feature_gates')
        if (value = attributes[:'disabled_feature_gates']).is_a?(Array)
          self.disabled_feature_gates = value
        end
      end

      if attributes.key?(:'disk_verification')
        self.disk_verification = attributes[:'disk_verification']
      end

      if attributes.key?(:'feature_gates')
        if (value = attributes[:'feature_gates']).is_a?(Array)
          self.feature_gates = value
        end
      end

      if attributes.key?(:'log_verbosity')
        self.log_verbosity = attributes[:'log_verbosity']
      end

      if attributes.key?(:'memory_overcommit')
        self.memory_overcommit = attributes[:'memory_overcommit']
      end

      if attributes.key?(:'minimum_cluster_tsc_frequency')
        self.minimum_cluster_tsc_frequency = attributes[:'minimum_cluster_tsc_frequency']
      end

      if attributes.key?(:'minimum_reserve_pvc_bytes')
        self.minimum_reserve_pvc_bytes = attributes[:'minimum_reserve_pvc_bytes']
      end

      if attributes.key?(:'node_selectors')
        if (value = attributes[:'node_selectors']).is_a?(Hash)
          self.node_selectors = value
        end
      end

      if attributes.key?(:'pvc_tolerate_less_space_up_to_percent')
        self.pvc_tolerate_less_space_up_to_percent = attributes[:'pvc_tolerate_less_space_up_to_percent']
      end

      if attributes.key?(:'use_emulation')
        self.use_emulation = attributes[:'use_emulation']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          cluster_profiler == o.cluster_profiler &&
          cpu_allocation_ratio == o.cpu_allocation_ratio &&
          disabled_feature_gates == o.disabled_feature_gates &&
          disk_verification == o.disk_verification &&
          feature_gates == o.feature_gates &&
          log_verbosity == o.log_verbosity &&
          memory_overcommit == o.memory_overcommit &&
          minimum_cluster_tsc_frequency == o.minimum_cluster_tsc_frequency &&
          minimum_reserve_pvc_bytes == o.minimum_reserve_pvc_bytes &&
          node_selectors == o.node_selectors &&
          pvc_tolerate_less_space_up_to_percent == o.pvc_tolerate_less_space_up_to_percent &&
          use_emulation == o.use_emulation
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [cluster_profiler, cpu_allocation_ratio, disabled_feature_gates, disk_verification, feature_gates, log_verbosity, memory_overcommit, minimum_cluster_tsc_frequency, minimum_reserve_pvc_bytes, node_selectors, pvc_tolerate_less_space_up_to_percent, use_emulation].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
