=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Kubevirt
  # KubeVirtStatus represents information pertaining to a KubeVirt deployment.
  class V1KubeVirtStatus < ApiModelBase
    attr_accessor :conditions

    attr_accessor :default_architecture

    attr_accessor :generations

    attr_accessor :observed_deployment_config

    attr_accessor :observed_deployment_id

    attr_accessor :observed_generation

    attr_accessor :observed_kube_virt_registry

    attr_accessor :observed_kube_virt_version

    attr_accessor :operator_version

    attr_accessor :outdated_virtual_machine_instance_workloads

    attr_accessor :phase

    attr_accessor :synchronization_addresses

    attr_accessor :target_deployment_config

    attr_accessor :target_deployment_id

    attr_accessor :target_kube_virt_registry

    attr_accessor :target_kube_virt_version

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'conditions' => :'conditions',
        :'default_architecture' => :'defaultArchitecture',
        :'generations' => :'generations',
        :'observed_deployment_config' => :'observedDeploymentConfig',
        :'observed_deployment_id' => :'observedDeploymentID',
        :'observed_generation' => :'observedGeneration',
        :'observed_kube_virt_registry' => :'observedKubeVirtRegistry',
        :'observed_kube_virt_version' => :'observedKubeVirtVersion',
        :'operator_version' => :'operatorVersion',
        :'outdated_virtual_machine_instance_workloads' => :'outdatedVirtualMachineInstanceWorkloads',
        :'phase' => :'phase',
        :'synchronization_addresses' => :'synchronizationAddresses',
        :'target_deployment_config' => :'targetDeploymentConfig',
        :'target_deployment_id' => :'targetDeploymentID',
        :'target_kube_virt_registry' => :'targetKubeVirtRegistry',
        :'target_kube_virt_version' => :'targetKubeVirtVersion'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'conditions' => :'Array<V1KubeVirtCondition>',
        :'default_architecture' => :'String',
        :'generations' => :'Array<V1GenerationStatus>',
        :'observed_deployment_config' => :'String',
        :'observed_deployment_id' => :'String',
        :'observed_generation' => :'Integer',
        :'observed_kube_virt_registry' => :'String',
        :'observed_kube_virt_version' => :'String',
        :'operator_version' => :'String',
        :'outdated_virtual_machine_instance_workloads' => :'Integer',
        :'phase' => :'String',
        :'synchronization_addresses' => :'Array<String>',
        :'target_deployment_config' => :'String',
        :'target_deployment_id' => :'String',
        :'target_kube_virt_registry' => :'String',
        :'target_kube_virt_version' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kubevirt::V1KubeVirtStatus` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kubevirt::V1KubeVirtStatus`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'conditions')
        if (value = attributes[:'conditions']).is_a?(Array)
          self.conditions = value
        end
      end

      if attributes.key?(:'default_architecture')
        self.default_architecture = attributes[:'default_architecture']
      end

      if attributes.key?(:'generations')
        if (value = attributes[:'generations']).is_a?(Array)
          self.generations = value
        end
      end

      if attributes.key?(:'observed_deployment_config')
        self.observed_deployment_config = attributes[:'observed_deployment_config']
      end

      if attributes.key?(:'observed_deployment_id')
        self.observed_deployment_id = attributes[:'observed_deployment_id']
      end

      if attributes.key?(:'observed_generation')
        self.observed_generation = attributes[:'observed_generation']
      end

      if attributes.key?(:'observed_kube_virt_registry')
        self.observed_kube_virt_registry = attributes[:'observed_kube_virt_registry']
      end

      if attributes.key?(:'observed_kube_virt_version')
        self.observed_kube_virt_version = attributes[:'observed_kube_virt_version']
      end

      if attributes.key?(:'operator_version')
        self.operator_version = attributes[:'operator_version']
      end

      if attributes.key?(:'outdated_virtual_machine_instance_workloads')
        self.outdated_virtual_machine_instance_workloads = attributes[:'outdated_virtual_machine_instance_workloads']
      end

      if attributes.key?(:'phase')
        self.phase = attributes[:'phase']
      end

      if attributes.key?(:'synchronization_addresses')
        if (value = attributes[:'synchronization_addresses']).is_a?(Array)
          self.synchronization_addresses = value
        end
      end

      if attributes.key?(:'target_deployment_config')
        self.target_deployment_config = attributes[:'target_deployment_config']
      end

      if attributes.key?(:'target_deployment_id')
        self.target_deployment_id = attributes[:'target_deployment_id']
      end

      if attributes.key?(:'target_kube_virt_registry')
        self.target_kube_virt_registry = attributes[:'target_kube_virt_registry']
      end

      if attributes.key?(:'target_kube_virt_version')
        self.target_kube_virt_version = attributes[:'target_kube_virt_version']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          conditions == o.conditions &&
          default_architecture == o.default_architecture &&
          generations == o.generations &&
          observed_deployment_config == o.observed_deployment_config &&
          observed_deployment_id == o.observed_deployment_id &&
          observed_generation == o.observed_generation &&
          observed_kube_virt_registry == o.observed_kube_virt_registry &&
          observed_kube_virt_version == o.observed_kube_virt_version &&
          operator_version == o.operator_version &&
          outdated_virtual_machine_instance_workloads == o.outdated_virtual_machine_instance_workloads &&
          phase == o.phase &&
          synchronization_addresses == o.synchronization_addresses &&
          target_deployment_config == o.target_deployment_config &&
          target_deployment_id == o.target_deployment_id &&
          target_kube_virt_registry == o.target_kube_virt_registry &&
          target_kube_virt_version == o.target_kube_virt_version
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [conditions, default_architecture, generations, observed_deployment_config, observed_deployment_id, observed_generation, observed_kube_virt_registry, observed_kube_virt_version, operator_version, outdated_virtual_machine_instance_workloads, phase, synchronization_addresses, target_deployment_config, target_deployment_id, target_kube_virt_registry, target_kube_virt_version].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
