=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Kubevirt
  # Probe describes a health check to be performed against a VirtualMachineInstance to determine whether it is alive or ready to receive traffic.
  class V1Probe < ApiModelBase
    attr_accessor :exec

    # Minimum consecutive failures for the probe to be considered failed after having succeeded. Defaults to 3. Minimum value is 1.
    attr_accessor :failure_threshold

    # GuestAgentPing configures the guest-agent based ping probe
    attr_accessor :guest_agent_ping

    attr_accessor :http_get

    # Number of seconds after the VirtualMachineInstance has started before liveness probes are initiated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
    attr_accessor :initial_delay_seconds

    # How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
    attr_accessor :period_seconds

    # Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness. Minimum value is 1.
    attr_accessor :success_threshold

    attr_accessor :tcp_socket

    # Number of seconds after which the probe times out. For exec probes the timeout fails the probe but does not terminate the command running on the guest. This means a blocking command can result in an increasing load on the guest. A small buffer will be added to the resulting workload exec probe to compensate for delays caused by the qemu guest exec mechanism. Defaults to 1 second. Minimum value is 1. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
    attr_accessor :timeout_seconds

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'exec' => :'exec',
        :'failure_threshold' => :'failureThreshold',
        :'guest_agent_ping' => :'guestAgentPing',
        :'http_get' => :'httpGet',
        :'initial_delay_seconds' => :'initialDelaySeconds',
        :'period_seconds' => :'periodSeconds',
        :'success_threshold' => :'successThreshold',
        :'tcp_socket' => :'tcpSocket',
        :'timeout_seconds' => :'timeoutSeconds'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'exec' => :'IoK8sApiCoreV1ExecAction',
        :'failure_threshold' => :'Integer',
        :'guest_agent_ping' => :'Object',
        :'http_get' => :'IoK8sApiCoreV1HTTPGetAction',
        :'initial_delay_seconds' => :'Integer',
        :'period_seconds' => :'Integer',
        :'success_threshold' => :'Integer',
        :'tcp_socket' => :'IoK8sApiCoreV1TCPSocketAction',
        :'timeout_seconds' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kubevirt::V1Probe` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kubevirt::V1Probe`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'exec')
        self.exec = attributes[:'exec']
      end

      if attributes.key?(:'failure_threshold')
        self.failure_threshold = attributes[:'failure_threshold']
      end

      if attributes.key?(:'guest_agent_ping')
        self.guest_agent_ping = attributes[:'guest_agent_ping']
      end

      if attributes.key?(:'http_get')
        self.http_get = attributes[:'http_get']
      end

      if attributes.key?(:'initial_delay_seconds')
        self.initial_delay_seconds = attributes[:'initial_delay_seconds']
      end

      if attributes.key?(:'period_seconds')
        self.period_seconds = attributes[:'period_seconds']
      end

      if attributes.key?(:'success_threshold')
        self.success_threshold = attributes[:'success_threshold']
      end

      if attributes.key?(:'tcp_socket')
        self.tcp_socket = attributes[:'tcp_socket']
      end

      if attributes.key?(:'timeout_seconds')
        self.timeout_seconds = attributes[:'timeout_seconds']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          exec == o.exec &&
          failure_threshold == o.failure_threshold &&
          guest_agent_ping == o.guest_agent_ping &&
          http_get == o.http_get &&
          initial_delay_seconds == o.initial_delay_seconds &&
          period_seconds == o.period_seconds &&
          success_threshold == o.success_threshold &&
          tcp_socket == o.tcp_socket &&
          timeout_seconds == o.timeout_seconds
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [exec, failure_threshold, guest_agent_ping, http_get, initial_delay_seconds, period_seconds, success_threshold, tcp_socket, timeout_seconds].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
