=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Kubevirt
  # VirtualMachineStatus represents the status returned by the controller to describe how the VirtualMachine is doing
  class V1VirtualMachineStatus < ApiModelBase
    attr_accessor :changed_block_tracking

    # Hold the state information of the VirtualMachine and its VirtualMachineInstance
    attr_accessor :conditions

    # Created indicates if the virtual machine is created in the cluster
    attr_accessor :created

    # DesiredGeneration is the generation which is desired for the VMI. This will be used in comparisons with ObservedGeneration to understand when the VMI is out of sync. This will be changed at the same time as ObservedGeneration to remove errors which could occur if Generation is updated through an Update() before ObservedGeneration in Status.
    attr_accessor :desired_generation

    attr_accessor :instancetype_ref

    attr_accessor :memory_dump_request

    # ObservedGeneration is the generation observed by the vmi when started.
    attr_accessor :observed_generation

    attr_accessor :preference_ref

    # PrintableStatus is a human readable, high-level representation of the status of the virtual machine
    attr_accessor :printable_status

    # Ready indicates if the virtual machine is running and ready
    attr_accessor :ready

    # RestoreInProgress is the name of the VirtualMachineRestore currently executing
    attr_accessor :restore_in_progress

    # RunStrategy tracks the last recorded RunStrategy used by the VM. This is needed to correctly process the next strategy (for now only the RerunOnFailure)
    attr_accessor :run_strategy

    # SnapshotInProgress is the name of the VirtualMachineSnapshot currently executing
    attr_accessor :snapshot_in_progress

    attr_accessor :start_failure

    # StateChangeRequests indicates a list of actions that should be taken on a VMI e.g. stop a specific VMI then start a new one.
    attr_accessor :state_change_requests

    # VolumeRequests indicates a list of volumes add or remove from the VMI template and hotplug on an active running VMI.
    attr_accessor :volume_requests

    # VolumeSnapshotStatuses indicates a list of statuses whether snapshotting is supported by each volume.
    attr_accessor :volume_snapshot_statuses

    attr_accessor :volume_update_state

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'changed_block_tracking' => :'changedBlockTracking',
        :'conditions' => :'conditions',
        :'created' => :'created',
        :'desired_generation' => :'desiredGeneration',
        :'instancetype_ref' => :'instancetypeRef',
        :'memory_dump_request' => :'memoryDumpRequest',
        :'observed_generation' => :'observedGeneration',
        :'preference_ref' => :'preferenceRef',
        :'printable_status' => :'printableStatus',
        :'ready' => :'ready',
        :'restore_in_progress' => :'restoreInProgress',
        :'run_strategy' => :'runStrategy',
        :'snapshot_in_progress' => :'snapshotInProgress',
        :'start_failure' => :'startFailure',
        :'state_change_requests' => :'stateChangeRequests',
        :'volume_requests' => :'volumeRequests',
        :'volume_snapshot_statuses' => :'volumeSnapshotStatuses',
        :'volume_update_state' => :'volumeUpdateState'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'changed_block_tracking' => :'V1ChangedBlockTrackingStatus',
        :'conditions' => :'Array<V1VirtualMachineCondition>',
        :'created' => :'Boolean',
        :'desired_generation' => :'Integer',
        :'instancetype_ref' => :'V1InstancetypeStatusRef',
        :'memory_dump_request' => :'V1VirtualMachineMemoryDumpRequest',
        :'observed_generation' => :'Integer',
        :'preference_ref' => :'V1InstancetypeStatusRef',
        :'printable_status' => :'String',
        :'ready' => :'Boolean',
        :'restore_in_progress' => :'String',
        :'run_strategy' => :'String',
        :'snapshot_in_progress' => :'String',
        :'start_failure' => :'V1VirtualMachineStartFailure',
        :'state_change_requests' => :'Array<V1VirtualMachineStateChangeRequest>',
        :'volume_requests' => :'Array<V1VirtualMachineVolumeRequest>',
        :'volume_snapshot_statuses' => :'Array<V1VolumeSnapshotStatus>',
        :'volume_update_state' => :'V1VolumeUpdateState'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kubevirt::V1VirtualMachineStatus` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kubevirt::V1VirtualMachineStatus`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'changed_block_tracking')
        self.changed_block_tracking = attributes[:'changed_block_tracking']
      end

      if attributes.key?(:'conditions')
        if (value = attributes[:'conditions']).is_a?(Array)
          self.conditions = value
        end
      end

      if attributes.key?(:'created')
        self.created = attributes[:'created']
      end

      if attributes.key?(:'desired_generation')
        self.desired_generation = attributes[:'desired_generation']
      end

      if attributes.key?(:'instancetype_ref')
        self.instancetype_ref = attributes[:'instancetype_ref']
      end

      if attributes.key?(:'memory_dump_request')
        self.memory_dump_request = attributes[:'memory_dump_request']
      end

      if attributes.key?(:'observed_generation')
        self.observed_generation = attributes[:'observed_generation']
      end

      if attributes.key?(:'preference_ref')
        self.preference_ref = attributes[:'preference_ref']
      end

      if attributes.key?(:'printable_status')
        self.printable_status = attributes[:'printable_status']
      end

      if attributes.key?(:'ready')
        self.ready = attributes[:'ready']
      end

      if attributes.key?(:'restore_in_progress')
        self.restore_in_progress = attributes[:'restore_in_progress']
      end

      if attributes.key?(:'run_strategy')
        self.run_strategy = attributes[:'run_strategy']
      end

      if attributes.key?(:'snapshot_in_progress')
        self.snapshot_in_progress = attributes[:'snapshot_in_progress']
      end

      if attributes.key?(:'start_failure')
        self.start_failure = attributes[:'start_failure']
      end

      if attributes.key?(:'state_change_requests')
        if (value = attributes[:'state_change_requests']).is_a?(Array)
          self.state_change_requests = value
        end
      end

      if attributes.key?(:'volume_requests')
        if (value = attributes[:'volume_requests']).is_a?(Array)
          self.volume_requests = value
        end
      end

      if attributes.key?(:'volume_snapshot_statuses')
        if (value = attributes[:'volume_snapshot_statuses']).is_a?(Array)
          self.volume_snapshot_statuses = value
        end
      end

      if attributes.key?(:'volume_update_state')
        self.volume_update_state = attributes[:'volume_update_state']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          changed_block_tracking == o.changed_block_tracking &&
          conditions == o.conditions &&
          created == o.created &&
          desired_generation == o.desired_generation &&
          instancetype_ref == o.instancetype_ref &&
          memory_dump_request == o.memory_dump_request &&
          observed_generation == o.observed_generation &&
          preference_ref == o.preference_ref &&
          printable_status == o.printable_status &&
          ready == o.ready &&
          restore_in_progress == o.restore_in_progress &&
          run_strategy == o.run_strategy &&
          snapshot_in_progress == o.snapshot_in_progress &&
          start_failure == o.start_failure &&
          state_change_requests == o.state_change_requests &&
          volume_requests == o.volume_requests &&
          volume_snapshot_statuses == o.volume_snapshot_statuses &&
          volume_update_state == o.volume_update_state
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [changed_block_tracking, conditions, created, desired_generation, instancetype_ref, memory_dump_request, observed_generation, preference_ref, printable_status, ready, restore_in_progress, run_strategy, snapshot_in_progress, start_failure, state_change_requests, volume_requests, volume_snapshot_statuses, volume_update_state].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
