=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Kubevirt
  # VirtualMachineSpec describes how the proper VirtualMachine should look like
  class V1VirtualMachineSpec < ApiModelBase
    # dataVolumeTemplates is a list of dataVolumes that the VirtualMachineInstance template can reference. DataVolumes in this list are dynamically created for the VirtualMachine and are tied to the VirtualMachine's life-cycle.
    attr_accessor :data_volume_templates

    attr_accessor :instancetype

    attr_accessor :preference

    # Running state indicates the requested running state of the VirtualMachineInstance mutually exclusive with Running Following are allowed values: - \"Always\": VMI should always be running. - \"Halted\": VMI should never be running. - \"Manual\": VMI can be started/stopped using API endpoints. - \"RerunOnFailure\": VMI will initially be running and restarted if a failure occurs, but will not be restarted upon successful completion. - \"Once\": VMI will run once and not be restarted upon completion regardless if the completion is of phase Failure or Success.
    attr_accessor :run_strategy

    # Running controls whether the associatied VirtualMachineInstance is created or not Mutually exclusive with RunStrategy Deprecated: VirtualMachineInstance field \"Running\" is now deprecated, please use RunStrategy instead.
    attr_accessor :running

    attr_accessor :template

    # UpdateVolumesStrategy is the strategy to apply on volumes updates
    attr_accessor :update_volumes_strategy

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'data_volume_templates' => :'dataVolumeTemplates',
        :'instancetype' => :'instancetype',
        :'preference' => :'preference',
        :'run_strategy' => :'runStrategy',
        :'running' => :'running',
        :'template' => :'template',
        :'update_volumes_strategy' => :'updateVolumesStrategy'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'data_volume_templates' => :'Array<V1DataVolumeTemplateSpec>',
        :'instancetype' => :'V1InstancetypeMatcher',
        :'preference' => :'V1PreferenceMatcher',
        :'run_strategy' => :'String',
        :'running' => :'Boolean',
        :'template' => :'V1VirtualMachineInstanceTemplateSpec',
        :'update_volumes_strategy' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kubevirt::V1VirtualMachineSpec` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kubevirt::V1VirtualMachineSpec`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'data_volume_templates')
        if (value = attributes[:'data_volume_templates']).is_a?(Array)
          self.data_volume_templates = value
        end
      end

      if attributes.key?(:'instancetype')
        self.instancetype = attributes[:'instancetype']
      end

      if attributes.key?(:'preference')
        self.preference = attributes[:'preference']
      end

      if attributes.key?(:'run_strategy')
        self.run_strategy = attributes[:'run_strategy']
      end

      if attributes.key?(:'running')
        self.running = attributes[:'running']
      end

      if attributes.key?(:'template')
        self.template = attributes[:'template']
      else
        self.template = nil
      end

      if attributes.key?(:'update_volumes_strategy')
        self.update_volumes_strategy = attributes[:'update_volumes_strategy']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @template.nil?
        invalid_properties.push('invalid value for "template", template cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @template.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] template Value to be assigned
    def template=(template)
      if template.nil?
        fail ArgumentError, 'template cannot be nil'
      end

      @template = template
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          data_volume_templates == o.data_volume_templates &&
          instancetype == o.instancetype &&
          preference == o.preference &&
          run_strategy == o.run_strategy &&
          running == o.running &&
          template == o.template &&
          update_volumes_strategy == o.update_volumes_strategy
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [data_volume_templates, instancetype, preference, run_strategy, running, template, update_volumes_strategy].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
