=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Kubevirt
  # DataVolumeSpec defines the DataVolume type specification
  class V1beta1DataVolumeSpec < ApiModelBase
    # Checkpoints is a list of DataVolumeCheckpoints, representing stages in a multistage import.
    attr_accessor :checkpoints

    # DataVolumeContentType options: \"kubevirt\", \"archive\"
    attr_accessor :content_type

    # FinalCheckpoint indicates whether the current DataVolumeCheckpoint is the final checkpoint.
    attr_accessor :final_checkpoint

    # Preallocation controls whether storage for DataVolumes should be allocated in advance.
    attr_accessor :preallocation

    # PriorityClassName for Importer, Cloner and Uploader pod
    attr_accessor :priority_class_name

    attr_accessor :pvc

    attr_accessor :source

    attr_accessor :source_ref

    attr_accessor :storage

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'checkpoints' => :'checkpoints',
        :'content_type' => :'contentType',
        :'final_checkpoint' => :'finalCheckpoint',
        :'preallocation' => :'preallocation',
        :'priority_class_name' => :'priorityClassName',
        :'pvc' => :'pvc',
        :'source' => :'source',
        :'source_ref' => :'sourceRef',
        :'storage' => :'storage'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'checkpoints' => :'Array<V1beta1DataVolumeCheckpoint>',
        :'content_type' => :'String',
        :'final_checkpoint' => :'Boolean',
        :'preallocation' => :'Boolean',
        :'priority_class_name' => :'String',
        :'pvc' => :'IoK8sApiCoreV1PersistentVolumeClaimSpec',
        :'source' => :'V1beta1DataVolumeSource',
        :'source_ref' => :'V1beta1DataVolumeSourceRef',
        :'storage' => :'V1beta1StorageSpec'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kubevirt::V1beta1DataVolumeSpec` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kubevirt::V1beta1DataVolumeSpec`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'checkpoints')
        if (value = attributes[:'checkpoints']).is_a?(Array)
          self.checkpoints = value
        end
      end

      if attributes.key?(:'content_type')
        self.content_type = attributes[:'content_type']
      end

      if attributes.key?(:'final_checkpoint')
        self.final_checkpoint = attributes[:'final_checkpoint']
      end

      if attributes.key?(:'preallocation')
        self.preallocation = attributes[:'preallocation']
      end

      if attributes.key?(:'priority_class_name')
        self.priority_class_name = attributes[:'priority_class_name']
      end

      if attributes.key?(:'pvc')
        self.pvc = attributes[:'pvc']
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      end

      if attributes.key?(:'source_ref')
        self.source_ref = attributes[:'source_ref']
      end

      if attributes.key?(:'storage')
        self.storage = attributes[:'storage']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          checkpoints == o.checkpoints &&
          content_type == o.content_type &&
          final_checkpoint == o.final_checkpoint &&
          preallocation == o.preallocation &&
          priority_class_name == o.priority_class_name &&
          pvc == o.pvc &&
          source == o.source &&
          source_ref == o.source_ref &&
          storage == o.storage
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [checkpoints, content_type, final_checkpoint, preallocation, priority_class_name, pvc, source, source_ref, storage].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
