=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Kubevirt
  # StorageSpec defines the Storage type specification
  class V1beta1StorageSpec < ApiModelBase
    # AccessModes contains the desired access modes the volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
    attr_accessor :access_modes

    attr_accessor :data_source

    attr_accessor :data_source_ref

    attr_accessor :resources

    attr_accessor :selector

    # Name of the StorageClass required by the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1
    attr_accessor :storage_class_name

    # volumeMode defines what type of volume is required by the claim. Value of Filesystem is implied when not included in claim spec.  Possible enum values:  - `\"Block\"` means the volume will not be formatted with a filesystem and will remain a raw block device.  - `\"Filesystem\"` means the volume will be or is formatted with a filesystem.  - `\"FromStorageProfile\"` means the volume mode will be auto selected by CDI according to a matching StorageProfile
    attr_accessor :volume_mode

    # VolumeName is the binding reference to the PersistentVolume backing this claim.
    attr_accessor :volume_name

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'access_modes' => :'accessModes',
        :'data_source' => :'dataSource',
        :'data_source_ref' => :'dataSourceRef',
        :'resources' => :'resources',
        :'selector' => :'selector',
        :'storage_class_name' => :'storageClassName',
        :'volume_mode' => :'volumeMode',
        :'volume_name' => :'volumeName'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'access_modes' => :'Array<String>',
        :'data_source' => :'IoK8sApiCoreV1TypedLocalObjectReference',
        :'data_source_ref' => :'IoK8sApiCoreV1TypedObjectReference',
        :'resources' => :'IoK8sApiCoreV1VolumeResourceRequirements',
        :'selector' => :'IoK8sApimachineryPkgApisMetaV1LabelSelector',
        :'storage_class_name' => :'String',
        :'volume_mode' => :'String',
        :'volume_name' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kubevirt::V1beta1StorageSpec` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kubevirt::V1beta1StorageSpec`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'access_modes')
        if (value = attributes[:'access_modes']).is_a?(Array)
          self.access_modes = value
        end
      end

      if attributes.key?(:'data_source')
        self.data_source = attributes[:'data_source']
      end

      if attributes.key?(:'data_source_ref')
        self.data_source_ref = attributes[:'data_source_ref']
      end

      if attributes.key?(:'resources')
        self.resources = attributes[:'resources']
      end

      if attributes.key?(:'selector')
        self.selector = attributes[:'selector']
      end

      if attributes.key?(:'storage_class_name')
        self.storage_class_name = attributes[:'storage_class_name']
      end

      if attributes.key?(:'volume_mode')
        self.volume_mode = attributes[:'volume_mode']
      end

      if attributes.key?(:'volume_name')
        self.volume_name = attributes[:'volume_name']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      volume_mode_validator = EnumAttributeValidator.new('String', ["Block", "Filesystem", "FromStorageProfile"])
      return false unless volume_mode_validator.valid?(@volume_mode)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] volume_mode Object to be assigned
    def volume_mode=(volume_mode)
      validator = EnumAttributeValidator.new('String', ["Block", "Filesystem", "FromStorageProfile"])
      unless validator.valid?(volume_mode)
        fail ArgumentError, "invalid value for \"volume_mode\", must be one of #{validator.allowable_values}."
      end
      @volume_mode = volume_mode
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          access_modes == o.access_modes &&
          data_source == o.data_source &&
          data_source_ref == o.data_source_ref &&
          resources == o.resources &&
          selector == o.selector &&
          storage_class_name == o.storage_class_name &&
          volume_mode == o.volume_mode &&
          volume_name == o.volume_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [access_modes, data_source, data_source_ref, resources, selector, storage_class_name, volume_mode, volume_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
